spring:
  datasource:
    dynamic:
      primary: basic-user
      strict: true
      datasource:
        basic-user:
          url: jdbc:mysql://127.0.0.1:3306/demo_user?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.zaxxer.hikari.HikariDataSource
mybatis-plus:
  mapper-locations:
    - classpath*:/org/smartframework/cloud/examples/basic/user/mapper/**/*.xml