smart:
  datasources:
    product:
      url: jdbc:mysql://127.0.0.1:3306/demo_product
      username: ENC(PbMw+RtvRPYAo4Acbuxe4Q==)
      password: ENC(IwbzHJPe93Wevq8LVx0AwQ==)
      mapper-interface-location: org.smartframework.cloud.examples.mall.product.mapper
      transaction-base-packages: org.smartframework.cloud.examples.mall.product.service
      mapper-xml-location: classpath*:/org/smartframework/cloud/examples/mall/product/mapper/**/*.xml
      seata-enable: true