spring:
  shardingsphere:
    datasource:
      names: mallordermaster-0, mallordermaster-1, mallorderslave-0, mallorderslave-1
      mallordermaster-0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/demo_order_0?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        username: root
        password: 123456
      mallordermaster-1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/demo_order_1?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        username: root
        password: 123456
      mallorderslave-0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/demo_order_0?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        username: root
        password: 123456
      mallorderslave-1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/demo_order_1?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        username: root
        password: 123456
    rules:
      readwrite-splitting:
        data-sources:
          mallorder0:
            type: Static
            props:
              write-data-source-names: mallordermaster-0
              read-data-source-names: mallorderslave-0
            load-balancer-name: round_robin
          mallorder1:
            type: Static
            props:
              write-data-source-name: mallordermaster-1
              read-data-source-names: mallorderslave-1
            load-balancer-name: round_robin
        load-balancers:
          round_robin:
            type: ROUND_ROBIN
      sharding:
        binding-tables: t_order_bill,t_order_delivery_info
        # 参考：https://github.com/apache/shardingsphere/blob/5.0.0/shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/test/resources/yaml/sharding-rule.yaml
        # https://github.com/apache/shardingsphere/blob/5.0.0/shardingsphere-features/shardingsphere-sharding/shardingsphere-sharding-core/src/test/resources/META-INF/services/org.apache.shardingsphere.sharding.spi.ShardingAlgorithm
        sharding-algorithms:
          order-bill-database-complex:
            type: ORDER_BILL_DATABASE_TYPE
          order-bill-table-complex:
            type: ORDER_BILL_TABLE_TYPE
          order-delivery-info-database-standard:
            type: ORDER_DELIVERY_INFO_DATABASE_TYPE
          order-delivery-info_table-standard:
            type: ORDER_DELIVERY_INFO_TABLE_TYPE
        tables:
          t_order_bill:
            actual-data-nodes: mallorder$->{0..1}.t_order_bill_$->{0..99}
            database-strategy:
              complex:
                sharding-algorithm-name: order-bill-database-complex
                sharding-columns: f_buyer,f_order_no
            table-strategy:
              complex:
                sharding-algorithm-name: order-bill-table-complex
                sharding-columns: f_buyer,f_order_no
          t_order_delivery_info:
            actual-data-nodes: mallorder$->{0..1}.t_order_delivery_info_$->{0..99}
            database-strategy:
              standard:
                sharding-algorithm-name: order-delivery-info-database-standard
                sharding-column: f_order_no
            table-strategy:
              standard:
                sharding-algorithm-name: order-delivery-info_table-standard
                sharding-column: f_order_no
    props:
      sql-show: true
mybatis-plus:
  mapper-locations:
    - classpath*:/org/smartframework/cloud/examples/mall/order/mapper/**/*.xml